{% set name = "nmslib" %}
{% set version = "2.1.1" %}

package:
  name: nmslib
  version: {{ version }}

source:
  url: https://github.com/nmslib/nmslib/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1f9cf1b63b5047ac13149abb0a319789db9096f49405020a3322914a151e7dc5
  patches:
    - patches/0001-remove-installation-requirements-handled-by-conda.patch
    # upstream has a cpu-guard that heckles people to compile from source if their
    # CPU supports more features than the library has been compiled with, see
    # https://github.com/nmslib/nmslib/blob/v2.1.1/python_bindings/tensorflow/cpu_feature_guard.cc#L158-L161
    # needless to say, we need to aim for portability here, and want to avoid
    # people following the instructions to install from pip, which might run
    # into various problems around ABIs of numpy/C++ etc.
    # Hopefully, we can provide more specific builds per CPU architecture
    # in the future, see conda-forge/conda-forge.github.io#1261
    - patches/0002-silence-log-that-tells-people-to-install-from-pip.patch
    # backport nmslib/nmslib#488 for compatibility with newer pybind11
    - patches/0003-Fix-import-on-newer-versions-of-pybind11-fixes-471.patch
    # some weird interaction with pybind11 + quote escapes;
    # upstream CI need quotes escaped, we need them unescaped
    - patches/0004-do-not-escape-quotes-for-VERSION_INFO.patch

build:
  number: 5
  script: {{ PYTHON }} -m pip install ./python_bindings -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - python
    - setuptools
    - psutil
    - pip
    - pybind11 >=2.2.3
    - numpy
  run:
    - python
    - pybind11 >=2.2.3
    - psutil

test:
  imports:
    - nmslib
  source_files:
    - python_bindings/tests
  requires:
    - pytest
  commands:
    {% set tests_to_skip = "_not_a_real_test" %}
    # skip a test that checks GC-behaviour for PyPy
    {% set tests_to_skip = tests_to_skip + " or testMemoryLeak" %}  # [python_impl == "pypy"]
    - pytest -v python_bindings/tests -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/searchivarius/nmslib
  summary: Non-Metric Space Library (NMSLIB)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jzthree
    - h-vetinari
